#!/data/data/com.termux/files/usr/bin/bash

q="-e"
e="echo "
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
v="4.2.0"
m="\033[1;31m"
h="\033[1;32m"
k="\033[1;33m"
b="\033[1;34m"
bl="\033[1;36m"
p="\033[1;37m"

play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
echo $q $bl
# Mendapatkan waktu saat ini
current_time=$(date +%H:%M)
# Menampilkan waktu saat ini
        clear
        bash $HOME/JARVIS/logo2.sh
        play -q $HOME/JARVIS/sound/robot.mp3 &>/dev/null &
        echo $q $b" ╔══════════════════════════════════════════════╗$b"
        echo $q $b" ║$h       WAKTU SAAT INI : $current_time                $b ║"
        echo $q $b" ╚══════════════════════════════════════════════╝$b"
# Mengambil input waktu alaram dari pengguna
read -p " MASUKKAN WAKTU ALARM (HH:MM): " alarm_time
# Mengubah waktu alaram menjadi detik
IFS=":" read -r hour minute <<< "$alarm_time"
alarm_in_seconds=$((10#$hour*3600 + 10#$minute*60))
# Mengubah waktu saat ini menjadi detik
IFS=":" read -r current_hour current_minute <<< "$current_time"
current_in_seconds=$((10#$current_hour*3600 + 10#$current_minute*60))
# Menghitung selisih waktu antara saat ini dan waktu alaram
time_diff=$((alarm_in_seconds - current_in_seconds))
# Menjalankan alaram setelah waktu tertentu
        clear                                                                                                    bash logo2.sh
        echo $q $b" ╔══════════════════════════════════════════════╗$b"
        echo $q $b" ║$h     ALARM AKAN DI PUTAR PADA JAM$m :$h $alarm_time    $b ║"
        echo $q $b" ╚══════════════════════════════════════════════╝$b"
        echo
        echo $q $b" ╔══════════════════════════════════════════════╗$b"
        echo $q $b" ║$m HARAP JANGAN KELUAR ATAU ALARAM AKAN GAGAL  $b ║"
        echo $q $b" ╚══════════════════════════════════════════════╝$b"
        play -q $HOME/JARVIS/sound/timeset.mp3 &>/dev/null
if [[ $time_diff -gt 0 ]]; then
 sleep "$time_diff"s

      clear
        bash $HOME/JARVIS/logo2.sh
        echo $q $b" ╔══════════════════════════════════════════════╗$b"
        echo $q $b" ║$h          WAKTU TELAH TIBA MODE ON           $b ║"
        echo $q $b" ╚══════════════════════════════════════════════╝$b"
        play -q $HOME/JARVIS/sound/waktunya2.mp3 &>/dev/null
	sleep 1
        play -q $HOME/JARVIS/sound/alaram.mp3 repeat &>/dev/null &
 read -p "ENTER UNTUK MENGHENTIKAN"
else
        clear
        bash $HOME/JARVIS/logo2.sh
        echo $q $b" ╔══════════════════════════════════════════════╗$b"
        echo $q $b" ║$m     WAKTU HARUS DI SETEL DENGAN BENAR       $b ║"
        echo $q $b" ╚══════════════════════════════════════════════╝$b"
        play -q $HOME/JARVIS/sound/salah.mp3 &>/dev/null
        play -q $HOME/JARVIS/sound/salah2.mp3 &>/dev/null
        sleep 3

fi
