#!/data/data/com.termux/files/usr/bin/bash
e="echo -e"
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
v="4.2.0"
m="\033[1;31m"
h="\033[1;32m"
k="\033[1;33m"
b="\033[1;34m"
bl="\033[1;36m"
p="\033[1;37m"	

ai="$HOME/gpt/GPT.py"
if [ -f "$ai" ]; then
play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
echo $q $h "klik$m CTRL C$h untuk Berhenti"
cd $HOME/gpt/
$e $k "PASSWORD :$m JB KONTOL"
sleep 3
python3 GPT.py

else
play -q $HOME/JARVIS/sound/salah.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/commandfalid.mp3 &>/dev/null &
echo "Installing Package"
cd $HOME
git clone https://github.com/Galirus404/gpt
cd gpt
git stash
git pull origin main
git add GPT.py
python3 $ai
fi
