#!/data/data/com.termux/files/usr/bin/bash

play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
am start -n com.mobile.legends/com.moba.unityplugin.MobaGameMainActivityWithExtractor
clear
