#!/data/data/com.termux/files/usr/bin/bash

tele="org.telegram.messenger/org.telegram.messenger.DefaultIcon"
play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
am start -n $tele
clear
