#!/data/data/com.termux/files/usr/bin/bash
e="echo -e"
s="sleep 1"
ss="sleep 2"
sss="sleep 3"
v="4.2.0"
m="\033[1;31m"
h="\033[1;32m"
k="\033[1;33m"
b="\033[1;34m"
bl="\033[1;36m"
p="\033[1;37m"	

tools="$HOME/TOOLSV5"
if [ -d "$tools" ]; then
play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
$e $k "TOOLSV5 TERINSTALL MENJALANKAN TOOLS !"
cd $tools
bash install.sh
clear

else
play -q $HOME/JARVIS/sound/salah.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/commandfalid.mp3 &>/dev/null
cd $HOME
$e $m "TOOLSV5 BELUM TERINSTALL installing package"
apt install git bash
git clone --depth 1 https://github.com/Galirus404/TOOLSV5
cd TOOLSV5
$e $k "TOOLS SUDAH TERINSTALL SILAHKAN ULANGI I"
sleep 3
clear
fi
