#!/data/data/com.termux/files/usr/bin/bash
wab="com.whatsapp.w4b/com.whatsapp.Main"
play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
am start -n $wab
clear
