#!/data/data/com.termux/files/usr/bin/bash


play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null play -q 
play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
	ulang="y"
while [  $ulang == "y" ]; do
	clear
	bash $HOME/JARVIS/logo2.sh
	play -q $HOME/JARVIS/sound/klik.mp3 &>/dev/null
	read -p "APA YANG MAU ANDA CARI : " cariyt
	play -q $HOME/JARVIS/sound/oke.mp3 &>/dev/null
	play -q $HOME/JARVIS/sound/robot2.mp3 &>/dev/null
xdg-open "https://www.youtube.com/results?search_query=$cariyt"
read -p "APA ANDA INGIN MENGULANG ? Y/N : " ulang
done

